import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Try Me | Store</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen w-full flex-col items-center bg-gradient-to-b from-black to-[#04100C]">
        <header className="max-w-screen fixed z-50 flex h-12 w-full items-center bg-[#1C4C40] px-2 text-white">
          <p>Try Me Logo here</p>
        </header>
        <main className="mt-12 flex h-full flex-col items-center bg-gradient-to-b from-black to-[#04100C]">
          {/* <h1 className="mb-6 text-8xl font-bold text-white">Try Me</h1> */}
          <Image
            src="/trumpet-trump.jpg"
            alt="picture of try me"
            width={1080}
            height={1080}
            className="object-contain"
          />
        </main>
        <div className="mt-4 rounded-full bg-white/10 p-4 text-white">
          <p className="bg-gradient-to-r from-fuchsia-400 via-white to-violet-500 bg-clip-text text-transparent">
            Bristol based duo with a jig in our step.
          </p>
        </div>
        <h2 className="mb-2 mt-4 text-2xl">Upcoming gigs</h2>
        <ul className="list-disc">
          <li>Exchange - 04/09/2023</li>
          <li>Mr Wolfs - 9/11/2023</li>
          <li>Glastonbury - 8/08/2030</li>
        </ul>
      </div>
    </>
  );
}
