import * as DropdownMenu from "@radix-ui/react-dropdown-menu";
import { HamburgerMenuIcon } from "@radix-ui/react-icons";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Try Me</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className="flex min-h-screen w-full flex-col items-center bg-gradient-to-b from-black to-[#04100C]">
        <header className="max-w-screen fixed z-50 flex w-full items-center justify-between bg-[#7DFCB2]/20 p-1 px-2 text-white">
          <DropdownMenu.Root>
            <DropdownMenu.Trigger asChild>
              <button className="IconButton" aria-label="Customise options">
                <HamburgerMenuIcon className="h-8 w-8" />
              </button>
            </DropdownMenu.Trigger>
          </DropdownMenu.Root>
          <Image
            src="/logo.png"
            alt="Try Me logo"
            width={64}
            height={64}
            className=""
          />
          <svg
            width="15"
            height="15"
            viewBox="0 0 15 15"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
            className="h-8 w-8"
          >
            <path
              d="M5 1C5 0.447715 5.44772 0 6 0H9C9.55228 0 10 0.447715 10 1V2H14C14.5523 2 15 2.44772 15 3V6C15 6.8888 14.6131 7.68734 14 8.23608V11.5C14 12.3284 13.3284 13 12.5 13H2.5C1.67157 13 1 12.3284 1 11.5V8.2359C0.38697 7.68721 0 6.88883 0 6V3C0 2.44772 0.447716 2 1 2H5V1ZM9 1V2H6V1H9ZM1 3H5H5.5H9.5H10H14V6C14 6.654 13.6866 7.23467 13.1997 7.6004C12.8655 7.85144 12.4508 8 12 8H8V7.5C8 7.22386 7.77614 7 7.5 7C7.22386 7 7 7.22386 7 7.5V8H3C2.5493 8 2.1346 7.85133 1.80029 7.60022C1.31335 7.23446 1 6.65396 1 6V3ZM7 9H3C2.64961 9 2.31292 8.93972 2 8.82905V11.5C2 11.7761 2.22386 12 2.5 12H12.5C12.7761 12 13 11.7761 13 11.5V8.82915C12.6871 8.93978 12.3504 9 12 9H8V9.5C8 9.77614 7.77614 10 7.5 10C7.22386 10 7 9.77614 7 9.5V9Z"
              fill="currentColor"
              fill-rule="evenodd"
              clip-rule="evenodd"
            ></path>
          </svg>
        </header>
        <main className="mt-[4.5rem] flex h-full w-full flex-col items-center bg-gradient-to-b from-black to-[#04100C]">
          {/* <h1 className="mb-6 text-8xl font-bold text-white">Try Me</h1> */}
          <Image
            src="/trumpet.jpg"
            alt="picture of try me"
            width={540}
            height={540}
            className="object-contain"
          />
          <p className="cool-text cool-shadow text-md w-full bg-white/10 bg-gradient-to-b from-black/20 via-white/20 to-black/20 py-6  text-center font-bold text-transparent text-white xxs:text-lg xs:text-xl  md:text-4xl">
            Bristol based duo with a jig in our step.
          </p>
          <div className="relative flex flex-col items-center">
            <Image
              src="/boombox.jpg"
              alt="try me on steps in funky trousers"
              width={850}
              height={1035}
            />
            <div className="absolute bottom-8 flex  flex-col rounded-full bg-white/10 bg-gradient-to-b from-black/40 via-black/80 to-black/40 p-4 text-center uppercase drop-shadow-xl xxs:text-lg xs:text-xl md:bottom-16 md:text-4xl">
              <p className="cool-text">
                &quot;...How Good is this from Try Me!?&quot;
              </p>
              <p>Jack Saunders BBC Radio 1</p>
            </div>
          </div>

          <h2 className="mb-2 mt-4 text-2xl">Upcoming gigs</h2>
          <table className="mx-2 table w-full bg-[#7DFCB2]/20 md:text-2xl">
            <thead className="border-b border-black">
              <tr className="divide-x divide-black">
                <th className="p-1 text-left">Venue</th>
                <th className="p-1 text-left">Date</th>
                <th className="p-1 text-left">Tix</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-black">
              <tr>
                <td>Exchange</td>
                <td>04/09/2023</td>
                <td> Link </td>
              </tr>
              <tr>
                <td>Mr Wolfs</td>
                <td>9/11/2023</td>
                <td> Link </td>
              </tr>
              <tr>
                <td>Glastonbury</td>
                <td>8/08/2030</td>
                <td> Link </td>
              </tr>
            </tbody>
          </table>
          <div className="relative w-full">
            <Image
              src="/gig.jpg"
              alt="try me on steps in funky trousers"
              width={3439}
              height={5159}
            />
            <div className="absolute top-0 flex h-full w-full items-center justify-center space-x-4 xs:space-x-8">
              <a className="opacity-90 xs:scale-125" href="">
                <Image
                  src="/facebook-logo.webp"
                  width={48}
                  height={48}
                  alt="facebook logo"
                />
              </a>
              <a className="opacity-90 xs:scale-125" href="">
                <Image
                  src="/instagram-logo.webp"
                  width={48}
                  height={48}
                  alt="instagram logo"
                />
              </a>
              <a className="opacity-90 invert xs:scale-125" href="">
                <Image
                  src="/tik-tok.png"
                  width={48}
                  height={48}
                  alt="tik tok logo"
                  className="bg-transparent"
                />
              </a>
              <a className="opacity-90 xs:scale-125" href="">
                <Image
                  src="/email-logo.png"
                  width={48}
                  height={48}
                  alt="email logo"
                />
              </a>
            </div>
          </div>
        </main>
      </div>
    </>
  );
}
